services:
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_SERVER_URL=http://localhost:8080
      - VITE_TILES_URL=http://localhost:8081

  backend:
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/mbtiles:/app/mbtiles
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MBTILES_ROOT=/app/mbtiles
    command: npm run dev

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8081:8080"
    volumes:
      - ./tileserver:/data
