export const PRESSURE_CONTOUR_INTERVAL_HPA = 4
export const PRESSURE_CONTOUR_MAIN_HALF_WIDTH_PX = 0.38
export const PRESSURE_CONTOUR_HALO_HALF_WIDTH_PX = 1.05
export const PRESSURE_CONTOUR_MAIN_ALPHA = 0.72
export const PRESSURE_CONTOUR_HALO_ALPHA = 0.18
export const PRESSURE_CONTOUR_SMOOTHING_KERNEL_WEIGHTS = [1, 2, 1, 2, 4, 2, 1, 2, 1] as const
export const PRESSURE_CONTOUR_MAIN_COLOR_RGB = [1, 1, 1] as const
export const PRESSURE_CONTOUR_HALO_COLOR_RGB = [0.07, 0.09, 0.12] as const
