server {
  listen 3000;

  add_header Access-Control-Allow-Origin "https://weather.zmbm.dev" always;
  add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
  add_header Access-Control-Allow-Headers "Origin, Accept, Content-Type" always;

  location /manifests/ {
    if ($request_method = OPTIONS) {
      return 204;
    }

    alias /data/public/manifests/;
    autoindex off;
    expires 60s;
  }

  location / {
    if ($request_method = OPTIONS) {
      return 204;
    }

    proxy_pass http://martin:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
