export {
  VECTOR_UPDATE_FRAGMENT_SHADER_SOURCE,
  VECTOR_UPDATE_VERTEX_SHADER_SOURCE,
} from './update'
export {
  VECTOR_PARTICLE_FRAGMENT_SHADER_SOURCE,
  VECTOR_PARTICLE_VERTEX_SHADER_SOURCE,
} from './particles'
export {
  VECTOR_TRAIL_FRAGMENT_SHADER_SOURCE,
  VECTOR_TRAIL_VERTEX_SHADER_SOURCE,
} from './trails'
