export const PRECIP_TYPE_SNOW_FRACTION_COMPONENT = 'snow_frac'
export const PRECIP_TYPE_MIX_FRACTION_COMPONENT = 'mix_frac'

export const PRECIP_TYPE_COMPONENTS = [
  PRECIP_TYPE_SNOW_FRACTION_COMPONENT,
  PRECIP_TYPE_MIX_FRACTION_COMPONENT,
] as const
